### ISSUE TITLE
Validação formulário

### ISSUE THREAD

**Issue by VALERIA-MATTOS** [VALERIA-MATTOS/crud#1]
**Problema:**
Formulário pode ser enviado vazio ou até mesmo ser preenchido com informações erradas, como por exemplo:
- Nome do produto com números;
- Deixar todas letras minúsculas;
- Valores e estoque com letras;
- Números negativos;
- Mais de um ponto no valor;
- Várias casas decimais depois do ponto.

**Solução**
Fazer a validação antes de ser dado o submit, informando ao usuário com alertas.

**Comment by kleinbruno** [comment]
ok

**Comment by VALERIA-MATTOS** [comment]
Faltou:
- Deixar letras minúsculas;
- Estoque não aceita ponto/vírgula;
- Valor máximo só permite até dezenas;

**Comment by kleinbruno** [comment]
ok
