### ISSUE TITLE
Pesquisar alternativo

### ISSUE THREAD

**Issue by VALERIA-MATTOS** [VALERIA-MATTOS/crud#3]
**Problema**
Do modo atual, apenas é possível fazer a pesquisa no select pelo nome do produto.

**Objetivo**
Incluir pesquisa através da id, produtos ativos e produtos inativos.

**Comment by kleinbruno** [comment]
fechar

**Comment by VALERIA-MATTOS** [comment]
Pesquisa apenas é feita pela ID.

**Comment by kleinbruno** [comment]
ok
