### ISSUE TITLE
Função para PUT, POST e DELETE

### ISSUE THREAD

**Issue by VALERIA-MATTOS** [VALERIA-MATTOS/crud#6]
**Problema**
A requisição por ajax é repetida, praticamente de igual modo, nas funções editar, postar e deletar.

**Objetivo**
Criar uma só função para os três métodos, mudando apenas o type, conforme cada situação.

**Comment by bakebak** [comment]
ok

**Comment by VALERIA-MATTOS** [comment]
Não foi feita.

**Comment by kleinbruno** [comment]
okay
